import { boolean, check, foreignKey, index, integer, jsonb, pgEnum, pgTable, text, timestamp, unique, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const providerEnum = pgEnum('provider_id', ['greenhouse', 'lever', 'ashby']);
export const permissionEnum = pgEnum('permission_status', ['APPROVED_FOR_SCOPE', 'UNKNOWN', 'BLOCKED']);
export const associationEnum = pgEnum('association_status', ['VERIFIED', 'UNVERIFIED']);
export const factApprovalEnum = pgEnum('fact_approval', ['SUGGESTED', 'USER_APPROVED', 'REJECTED']);
export const applicationStateEnum = pgEnum('application_state', ['DRAFT', 'PREPARING', 'REVIEW_REQUIRED', 'READY', 'IN_PROGRESS', 'UNKNOWN', 'CONFIRMED', 'CANCELLED']);
export const recruitmentStageEnum = pgEnum('recruitment_stage', ['NO_RESPONSE', 'RECRUITER_CONTACT', 'ASSESSMENT', 'INTERVIEW', 'FINAL_INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', 'HIRED']);
export const shortlistEnum = pgEnum('shortlist_decision', ['UNREVIEWED', 'SHORTLISTED', 'SKIPPED', 'ARCHIVED']);
export const availabilityEnum = pgEnum('job_availability', ['OPEN', 'POSSIBLY_CLOSED', 'CLOSED', 'UNKNOWN']);

const created = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const changed = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();

export const workspaces = pgTable('workspaces', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: varchar('name', { length: 160 }).notNull().default('My career workspace'),
  timezone: varchar('timezone', { length: 100 }).notNull().default('Europe/Madrid'),
  createdAt: created(), updatedAt: changed(),
});

export const profileVersions = pgTable('profile_versions', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }),
  revision: integer('revision').notNull(), locale: varchar('locale', { length: 20 }).notNull().default('en-GB'), profile: jsonb('profile').$type<Record<string, unknown>>().notNull().default({}), createdAt: created(),
}, (t) => [uniqueIndex('profile_versions_workspace_revision_uq').on(t.workspaceId, t.revision), unique('profile_versions_workspace_id_uq').on(t.workspaceId, t.id)]);

export const profileFacts = pgTable('profile_facts', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull(), profileVersionId: uuid('profile_version_id').notNull(), kind: varchar('kind', { length: 64 }).notNull(), statement: text('statement').notNull(), tags: jsonb('tags').$type<string[]>().notNull().default([]), source: varchar('source', { length: 40 }).notNull().default('USER_ENTERED'), approvalStatus: factApprovalEnum('approval_status').notNull().default('SUGGESTED'), approvedAt: timestamp('approved_at', { withTimezone: true }), createdAt: created(),
}, (t) => [foreignKey({ columns: [t.workspaceId, t.profileVersionId], foreignColumns: [profileVersions.workspaceId, profileVersions.id], name: 'profile_facts_workspace_revision_fk' }).onDelete('cascade'), index('profile_facts_workspace_approval_idx').on(t.workspaceId, t.approvalStatus)]);

export const answerVersions = pgTable('answer_versions', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), semanticKey: varchar('semantic_key', { length: 100 }).notNull(), jurisdiction: varchar('jurisdiction', { length: 2 }).notNull(), questionScope: varchar('question_scope', { length: 160 }).notNull(), questionText: varchar('question_text', { length: 500 }), value: jsonb('value'), strategy: varchar('strategy', { length: 40 }).notNull(), approvalStatus: varchar('approval_status', { length: 30 }).notNull().default('UNANSWERED'), reviewAfter: timestamp('review_after', { withTimezone: true }), revision: integer('revision').notNull(), createdAt: created(),
}, (t) => [uniqueIndex('answer_versions_workspace_key_jurisdiction_scope_revision_uq').on(t.workspaceId, t.semanticKey, t.jurisdiction, t.questionScope, t.revision)]);

export const boards = pgTable('boards', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), provider: providerEnum('provider').notNull(), tenant: varchar('tenant', { length: 200 }).notNull(), region: varchar('region', { length: 40 }).notNull(), companyName: varchar('company_name', { length: 200 }).notNull(), companyDomain: varchar('company_domain', { length: 253 }).notNull(), careersUrl: text('careers_url').notNull(), associationStatus: associationEnum('association_status').notNull().default('UNVERIFIED'), permissionStatus: permissionEnum('permission_status').notNull().default('UNKNOWN'), allowedApplicationOrigins: jsonb('allowed_application_origins').$type<string[]>().notNull().default([]), enabled: boolean('enabled').notNull().default(false), reviewedAt: timestamp('reviewed_at', { withTimezone: true }), reviewDueAt: timestamp('review_due_at', { withTimezone: true }), lastSuccessfulRefreshAt: timestamp('last_successful_refresh_at', { withTimezone: true }), createdAt: created(), updatedAt: changed(),
}, (t) => [unique('boards_workspace_id_uq').on(t.workspaceId, t.id), uniqueIndex('boards_workspace_provider_region_tenant_uq').on(t.workspaceId, t.provider, t.region, t.tenant), index('boards_workspace_enabled_idx').on(t.workspaceId, t.enabled)]);

export const jobs = pgTable('jobs', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), company: varchar('company', { length: 200 }).notNull(), title: varchar('title', { length: 300 }).notNull(), location: varchar('location', { length: 300 }), canonicalUrl: text('canonical_url'), availability: availabilityEnum('availability').notNull().default('UNKNOWN'), shortlistDecision: shortlistEnum('shortlist_decision').notNull().default('UNREVIEWED'), fitScore: integer('fit_score'), evidenceCoverage: integer('evidence_coverage'), eligibility: varchar('eligibility', { length: 20 }).notNull().default('NEEDS_REVIEW'), reasons: jsonb('reasons').$type<string[]>().notNull().default([]), createdAt: created(), updatedAt: changed(),
}, (t) => [unique('jobs_workspace_id_uq').on(t.workspaceId, t.id), index('jobs_workspace_availability_idx').on(t.workspaceId, t.availability)]);

export const jobOccurrences = pgTable('job_occurrences', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull(), jobId: uuid('job_id').notNull(), provider: providerEnum('provider').notNull(), region: varchar('region', { length: 40 }).notNull(), tenant: varchar('tenant', { length: 200 }).notNull(), externalJobId: varchar('external_job_id', { length: 300 }).notNull(), jobUrl: text('job_url').notNull(), applyUrl: text('apply_url'), sourcePostedAt: timestamp('source_posted_at', { withTimezone: true }), sourceUpdatedAt: timestamp('source_updated_at', { withTimezone: true }), firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(), lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(), lastSuccessfulRefreshAt: timestamp('last_successful_refresh_at', { withTimezone: true }), sourcePayload: jsonb('source_payload').$type<Record<string, unknown>>().notNull(),
}, (t) => [foreignKey({ columns: [t.workspaceId, t.jobId], foreignColumns: [jobs.workspaceId, jobs.id], name: 'job_occurrences_workspace_job_fk' }).onDelete('cascade'), uniqueIndex('job_occurrences_identity_uq').on(t.workspaceId, t.provider, t.region, t.tenant, t.externalJobId)]);

export const jobSnapshots = pgTable('job_snapshots', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull(), jobId: uuid('job_id').notNull(), occurrenceId: uuid('occurrence_id'), title: varchar('title', { length: 300 }).notNull(), descriptionText: text('description_text'), snapshotHash: varchar('snapshot_hash', { length: 64 }).notNull(), fetchedAt: timestamp('fetched_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.workspaceId, t.jobId], foreignColumns: [jobs.workspaceId, jobs.id], name: 'job_snapshots_workspace_job_fk' }).onDelete('cascade'), unique('job_snapshots_workspace_id_uq').on(t.workspaceId, t.id)]);

export const applications = pgTable('applications', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), jobId: uuid('job_id'), applicationCycle: integer('application_cycle').notNull().default(1), company: varchar('company', { length: 200 }).notNull(), role: varchar('role', { length: 300 }).notNull(), location: varchar('location', { length: 300 }), canonicalUrl: text('canonical_url'), state: applicationStateEnum('state').notNull().default('DRAFT'), recruitmentStage: recruitmentStageEnum('recruitment_stage').notNull().default('NO_RESPONSE'), shortlistDecision: shortlistEnum('shortlist_decision').notNull().default('UNREVIEWED'), notes: text('notes').notNull().default(''), version: integer('version').notNull().default(1), createdAt: created(), updatedAt: changed(),
}, (t) => [foreignKey({ columns: [t.workspaceId, t.jobId], foreignColumns: [jobs.workspaceId, jobs.id], name: 'applications_workspace_job_fk' }), unique('applications_workspace_id_uq').on(t.workspaceId, t.id), uniqueIndex('applications_workspace_job_cycle_uq').on(t.workspaceId, t.jobId, t.applicationCycle), index('applications_workspace_state_idx').on(t.workspaceId, t.state, t.updatedAt)]);

export const applicationEvents = pgTable('application_events', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), applicationId: uuid('application_id').notNull().references(() => applications.id, { onDelete: 'cascade' }), actor: varchar('actor', { length: 80 }).notNull().default('USER'), eventType: varchar('event_type', { length: 100 }).notNull(), reason: text('reason'), priorState: varchar('prior_state', { length: 40 }), newState: varchar('new_state', { length: 40 }), evidence: jsonb('evidence').$type<Record<string, unknown>>(), aggregateVersion: integer('aggregate_version').notNull(), createdAt: created(),
}, (t) => [foreignKey({ columns: [t.workspaceId, t.applicationId], foreignColumns: [applications.workspaceId, applications.id], name: 'application_events_workspace_application_fk' }).onDelete('cascade'), index('application_events_workspace_application_idx').on(t.workspaceId, t.applicationId, t.createdAt)]);

export const documentVersions = pgTable('document_versions', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), name: varchar('name', { length: 200 }).notNull(), revision: integer('revision').notNull(), profileRevisionId: uuid('profile_revision_id'), jobSnapshotId: uuid('job_snapshot_id'), mediaType: varchar('media_type', { length: 120 }).notNull(), storagePath: text('storage_path').notNull(), sha256: varchar('sha256', { length: 64 }).notNull(), claims: jsonb('claims').$type<Array<{ text: string; sourceFactIds: string[]; approvalStatus: string }>>().notNull().default([]), approvalStatus: varchar('approval_status', { length: 30 }).notNull().default('PENDING_REVIEW'), createdAt: created(),
}, (t) => [foreignKey({ columns: [t.workspaceId, t.profileRevisionId], foreignColumns: [profileVersions.workspaceId, profileVersions.id], name: 'document_versions_workspace_profile_revision_fk' }), foreignKey({ columns: [t.workspaceId, t.jobSnapshotId], foreignColumns: [jobSnapshots.workspaceId, jobSnapshots.id], name: 'document_versions_workspace_job_snapshot_fk' }), uniqueIndex('document_versions_workspace_name_revision_uq').on(t.workspaceId, t.name, t.revision), index('document_versions_workspace_created_idx').on(t.workspaceId, t.createdAt)]);

export const llmUsage = pgTable('llm_usage', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), provider: varchar('provider', { length: 80 }).notNull(), model: varchar('model', { length: 160 }).notNull(), operation: varchar('operation', { length: 100 }).notNull(), status: varchar('status', { length: 30 }).notNull(), inputTokens: integer('input_tokens'), outputTokens: integer('output_tokens'), costUsd: text('cost_usd'), createdAt: created() });

export const deletionJobs = pgTable('deletion_jobs', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), status: varchar('status', { length: 30 }).notNull().default('PENDING'), requestedAt: created(), completedAt: timestamp('completed_at', { withTimezone: true }) });

export const sourcePolicyReviews = pgTable('source_policy_reviews', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull(), boardId: uuid('board_id').notNull().references(() => boards.id, { onDelete: 'cascade' }), capability: varchar('capability', { length: 50 }).notNull(), accessClass: varchar('access_class', { length: 60 }).notNull(), permissionStatus: permissionEnum('permission_status').notNull(), apiHost: varchar('api_host', { length: 255 }).notNull(), referenceUrl: text('reference_url'), notes: text('notes').notNull().default(''), adapterVersion: varchar('adapter_version', { length: 80 }).notNull(), fixtureCoverage: integer('fixture_coverage').notNull().default(0), reviewedAt: timestamp('reviewed_at', { withTimezone: true }).notNull(), reviewDueAt: timestamp('review_due_at', { withTimezone: true }), createdAt: created(),
}, (t) => [foreignKey({ columns: [t.workspaceId, t.boardId], foreignColumns: [boards.workspaceId, boards.id], name: 'source_policy_workspace_board_fk' }).onDelete('cascade'), check('source_policy_fixture_coverage_check', sql`${t.fixtureCoverage} between 0 and 100`)]);

export const searchProfiles = pgTable('search_profiles', {
  id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), name: varchar('name', { length: 160 }).notNull(), targetTitles: jsonb('target_titles').$type<string[]>().notNull().default([]), countries: jsonb('countries').$type<string[]>().notNull().default([]), workModes: jsonb('work_modes').$type<string[]>().notNull().default([]), unknownLocationPolicy: varchar('unknown_location_policy', { length: 40 }).notNull().default('NEEDS_REVIEW'), maximumPostedAgeDays: integer('maximum_posted_age_days').notNull().default(14), enabled: boolean('enabled').notNull().default(false), boardIds: jsonb('board_ids').$type<string[]>().notNull().default([]), createdAt: created(), updatedAt: changed(),
});
