export const JOB_SEARCH_PROVIDER_COOLDOWN_MS = 6 * 60 * 60 * 1000;
export const JOB_SEARCH_INTERVAL_MS = JOB_SEARCH_PROVIDER_COOLDOWN_MS;
export const JOB_SEARCH_FAILURE_MAX_MS = 48 * 60 * 60 * 1000;
