import assert from 'node:assert/strict';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {readFile,readdir} from 'node:fs/promises';
import {before,after,beforeEach,describe,test} from 'node:test';
import Fastify, {type FastifyInstance} from 'fastify';
import type {Client as PgClient} from 'pg';
import {ProviderReadError} from '../src/job-search-sources.js';
import type {PublicJob} from '../src/job-search-sources.js';
import type {SearchProvider} from '../src/search-execution.js';
const root=new URL('../../../',import.meta.url);
const {Client}=createRequire(new URL('packages/db/package.json',root))('pg');
const adminUrl=process.env.CAREER_JOB_SEARCH_TEST_ADMIN_URL;
const name=`career_search_v080_${randomBytes(6).toString('hex')}`;
describe('v0.8 persisted search execution in disposable database',{skip:!adminUrl,concurrency:false},()=>{
 let admin:PgClient|undefined,client!:PgClient,workspace:string,dbmod:typeof import('@career/db'),routes:typeof import('../src/job-search-routes.js'),execution:typeof import('../src/search-execution.js');
 before(async()=>{const url=new URL(adminUrl!);assert.ok(['127.0.0.1','localhost'].includes(url.hostname));assert.equal(url.pathname,'/postgres');admin=new Client({connectionString:url.toString()});await admin.connect();await admin.query(`CREATE DATABASE "${name}"`);url.pathname=`/${name}`;process.env.DATABASE_URL=url.toString();client=new Client({connectionString:url.toString()});await client.connect();for(const file of (await readdir(new URL('packages/db/migrations',root))).filter(f=>f.endsWith('.sql')).sort()) await client.query(await readFile(new URL(`packages/db/migrations/${file}`,root),'utf8'));[dbmod,routes,execution]=await Promise.all([import('@career/db'),import('../src/job-search-routes.js'),import('../src/search-execution.js')]);});
 after(async()=>{await dbmod?.pool.end();await client?.end();if(admin){await admin.query(`DROP DATABASE IF EXISTS "${name}" WITH(FORCE)`);await admin.end();}});
 beforeEach(async()=>{await client.query('DELETE FROM search_query_cache');await client.query('DELETE FROM search_provider_budget');await client.query('DELETE FROM workspaces');workspace=randomUUID();await client.query('INSERT INTO workspaces(id) VALUES($1)',[workspace]);});
 const server=():FastifyInstance=>{const app=Fastify();routes.registerJobSearchRoutes(app,()=>workspace);return app;};
 const payload=(patch:Record<string,unknown>={})=>({role:'QA',company:null,location:null,workMode:'any',frequencyHours:24,enabled:true,autoPrepare:false,language:'en',matcherVersion:2,providerIds:['remotive','arbeitnow'],includeRelated:false,idempotencyKey:randomUUID(),...patch});
 const job=(id='1',patch:Partial<PublicJob>={})=>({externalId:id,title:'QA Engineer',company:'Fictional',location:'Spain',workMode:'remote',url:`https://example.test/jobs/${id}`,description:'Test interfaces and document defects.',postedAt:'2026-10-01T00:00:00.000Z',raw:{},...patch});
 const feed=(jobs:PublicJob[],coverage:'COMPLETE'|'BOUNDED'|'PARTIAL'='COMPLETE')=>({jobs,state:'FRESH',coverage,fetchedAt:new Date()});
 const createSearch=async(app:FastifyInstance,patch:Record<string,unknown>={})=>{const response=await app.inject({method:'POST',url:'/api/v1/job-searches',payload:payload(patch)});assert.equal(response.statusCode,201,response.body);return response.json();};
 const seedPreparationMatch=async(searchId:string,options:{title?:string;description?:string|null;unknown?:boolean;reasons?:string[];decision?:string;identity?:string;applicationState?:string;jobId?:string;workspaceId?:string}={})=>{
  const jobId=options.jobId??randomUUID();const workspaceId=options.workspaceId??workspace;const url=`https://jobs.fictional.example/jobs/${jobId}`;const identity=options.identity??createHash('sha256').update(url).digest('hex');
  await client.query(`INSERT INTO jobs(id,workspace_id,title,company,location,canonical_url,availability,shortlist_decision) VALUES($1,$2,$3,'Fictional','Spain',$4,'OPEN',$5)`,[jobId,workspaceId,options.title??'QA Engineer',url,options.decision??'UNREVIEWED']);
  if(options.description!==null) await client.query(`INSERT INTO job_snapshots(workspace_id,job_id,title,description_text,snapshot_hash) VALUES($1,$2,$3,$4,$5)`,[workspaceId,jobId,options.title??'QA Engineer',options.description??'Usable fictional job description.',createHash('sha256').update(jobId).digest('hex')]);
  await client.query(`INSERT INTO saved_job_search_matches(workspace_id,search_id,job_id) VALUES($1,$2,$3)`,[workspaceId,searchId,jobId]);
  const run=(await client.query(`SELECT id FROM search_runs WHERE search_id=$1 ORDER BY created_at DESC LIMIT 1`,[searchId])).rows[0];assert.ok(run);
  await client.query(`INSERT INTO search_run_results(workspace_id,run_id,search_id,job_id,score,reasons,location_status,unknown_location,posted_at,sources) VALUES($1,$2,$3,$4,90,$5::jsonb,$6,$7,NULL,'[]'::jsonb)`,[workspaceId,run.id,searchId,jobId,JSON.stringify(options.reasons??[]),options.unknown?'unknown':'compatible',options.unknown??false]);
  await client.query(`INSERT INTO job_identity_members(workspace_id,job_id,identity_key,evidence) VALUES($1,$2,$3,'{}'::jsonb)`,[workspaceId,jobId,identity]);
  if(options.applicationState) await client.query(`INSERT INTO applications(workspace_id,job_id,company,role,state,shortlist_decision,notes) VALUES($1,$2,'Fictional','QA Engineer',$3,'SHORTLISTED','selected manually')`,[workspaceId,jobId,options.applicationState]);
  return jobId;
 };
 test('create is immediate and idempotent; workers group strong duplicate identities for review',async()=>{const app=server();try{const p=payload();const [a,b]=await Promise.all([app.inject({method:'POST',url:'/api/v1/job-searches',payload:p}),app.inject({method:'POST',url:'/api/v1/job-searches',payload:p})]);assert.equal(a.statusCode,201,a.body);assert.equal(b.statusCode,201,b.body);assert.equal(a.json().search.id,b.json().search.id);assert.equal(a.json().runId,b.json().runId);assert.equal((await client.query('SELECT count(*)::int n FROM search_runs')).rows[0].n,1);await execution.runSearchExecutionTick(async p=>feed([job(p,{url:`https://example.test/jobs/shared?utm_source=${p}`})]));const result=await app.inject(`/api/v1/job-searches/${a.json().search.id}/results?view=new`);assert.equal(result.statusCode,200,result.body);assert.equal(result.json().latestRun.status,'SUCCEEDED',JSON.stringify(result.json().latestRun));assert.equal(result.json().total,1);assert.equal(result.json().items[0].duplicateCount,1);assert.equal(result.json().items[0].sources.length,2);const jid=result.json().items[0].id;assert.equal((await app.inject({method:'POST',url:`/api/v1/job-searches/${a.json().search.id}/results/${jid}/review`})).statusCode,200);assert.equal((await app.inject(`/api/v1/job-searches/${a.json().search.id}/results?view=new`)).json().total,0);assert.equal((await app.inject('/api/v1/job-searches/results?view=all')).json().total,1);}finally{await app.close();}});
 test('revision conflicts and pause fence a late source response',async()=>{const app=server();try{const a=(await app.inject({method:'POST',url:'/api/v1/job-searches',payload:payload()})).json();let release!:()=>void;let started!:()=>void;const ready=new Promise<void>(r=>started=r),wait=new Promise<void>(r=>release=r);const tick=execution.runSearchExecutionTick(async()=>{started();await wait;return feed([job()]);});await ready;const edit=await app.inject({method:'PATCH',url:`/api/v1/job-searches/${a.search.id}`,payload:{expectedRevision:1,enabled:false}});assert.equal(edit.statusCode,200,edit.body);assert.equal((await app.inject({method:'PATCH',url:`/api/v1/job-searches/${a.search.id}`,payload:{expectedRevision:1,role:'designer'}})).statusCode,409);release();await tick;assert.equal((await client.query('SELECT count(*)::int n FROM jobs')).rows[0].n,0);assert.equal((await client.query('SELECT status FROM search_runs')).rows[0].status,'CANCELLED');}finally{await app.close();}});
 test('partial results visible before slow provider, failed refresh preserves prior publication',async()=>{const app=server();try{const a=(await app.inject({method:'POST',url:'/api/v1/job-searches',payload:payload()})).json();let release!:()=>void;const wait=new Promise<void>(r=>release=r);const tick=execution.runSearchExecutionTick(async p=>{if(p==='arbeitnow')await wait;return feed([job(p)]);});for(let i=0;i<100;i++){if((await client.query('SELECT count(*)::int n FROM search_run_results')).rows[0].n)break;await new Promise(r=>setTimeout(r,10));}const partial=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json();assert.equal(partial.total,1);assert.equal(partial.latestRun.finishedAt,null);release();await tick;await app.inject({method:'POST',url:`/api/v1/job-searches/${a.search.id}/refresh`});await execution.runSearchExecutionTick(async()=>{throw new Error('fixture timeout');});const result=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json();assert.equal(result.total,2);assert.equal(result.latestRun.status,'FAILED');}finally{await app.close();}});
 test('expired leases recover once, parallel ticks share a single claim',async()=>{const app=server();try{const a=(await app.inject({method:'POST',url:'/api/v1/job-searches',payload:payload({providerIds:['remotive']})})).json();await client.query("UPDATE search_runs SET status='RUNNING',owner=$1,lease_until=now()-interval '1 minute' WHERE id=$2",[randomUUID(),a.runId]);let calls=0;await Promise.all([execution.runSearchExecutionTick(async()=>{calls++;return feed([job()]);}),execution.runSearchExecutionTick(async()=>{calls++;return feed([job()]);})]);assert.equal(calls,1);assert.equal((await client.query('SELECT count(*)::int n FROM jobs')).rows[0].n,1);}finally{await app.close();}});
 test('results and review are scoped to workspace and invalid IDs are safe',async()=>{const app=server();try{const a=(await app.inject({method:'POST',url:'/api/v1/job-searches',payload:payload()})).json();await execution.runSearchExecutionTick(async()=>feed([job()]));const jid=(await client.query('SELECT id FROM jobs')).rows[0].id;workspace=randomUUID();await client.query('INSERT INTO workspaces(id) VALUES($1)',[workspace]);assert.equal((await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).statusCode,404);assert.equal((await app.inject('/api/v1/job-searches/results')).json().total,0);assert.equal((await app.inject({method:'POST',url:`/api/v1/job-searches/all/results/${jid}/review`})).statusCode,404);assert.equal((await app.inject('/api/v1/job-searches/nonsense/results')).statusCode,404);}finally{await app.close();}});

 test('PARTIAL feed coverage is persisted and makes a completed run PARTIAL',async()=>{const app=server();try{const a=await createSearch(app,{providerIds:['remotive']});await execution.runSearchExecutionTick(async()=>feed([job()], 'PARTIAL'));const result=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json();assert.equal(result.total,1);assert.equal(result.latestRun.status,'PARTIAL');assert.equal(result.latestRun.sources[0].coverage,'PARTIAL');}finally{await app.close();}});

 test('a single provider failure retains that contribution while another source succeeds',async()=>{const app=server();try{const a=await createSearch(app);await execution.runSearchExecutionTick(async p=>feed([job(p)]));const before=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json();assert.equal(before.total,2);await app.inject({method:'POST',url:`/api/v1/job-searches/${a.search.id}/refresh`});await execution.runSearchExecutionTick(async p=>{if(p==='remotive')throw new Error('fictional timeout');return feed([]);});const after=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json();assert.equal(after.total,1);assert.equal(after.latestRun.status,'PARTIAL');assert.equal(after.items.reduce((n:number,item:{sources:unknown[]})=>n+item.sources.length,0),1);assert.equal((await client.query(`SELECT count(*)::int n FROM jobs WHERE availability='OPEN'`)).rows[0].n,2);}finally{await app.close();}});

 test('a successful complete refresh replaces only its own carried source contribution',async()=>{const app=server();try{const a=await createSearch(app);const shared=job('shared',{url:'https://example.test/jobs/shared'});await execution.runSearchExecutionTick(async()=>feed([shared]));const before=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json();assert.equal(before.items[0].sources.length,2);await app.inject({method:'POST',url:`/api/v1/job-searches/${a.search.id}/refresh`});await execution.runSearchExecutionTick(async provider=>{if(provider==='arbeitnow')throw new Error('fixture provider timeout');return feed([]);});const after=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json();assert.equal(after.total,1);assert.deepEqual(after.items[0].sources.map((source:{provider:string})=>source.provider),['arbeitnow']);assert.equal((await client.query(`SELECT availability FROM jobs WHERE id=$1`,[after.items[0].id])).rows[0].availability,'OPEN');}finally{await app.close();}});

 test('retry after a deferred source does not restore already-replaced provider jobs',async()=>{const app=server();try{const a=await createSearch(app);await execution.runSearchExecutionTick(async provider=>feed([job(provider,{url:`https://example.test/jobs/${provider}`})]));await app.inject({method:'POST',url:`/api/v1/job-searches/${a.search.id}/refresh`});await execution.runSearchExecutionTick(async provider=>{if(provider==='arbeitnow')throw new ProviderReadError('SOURCE_BUSY',Date.now()+120_000);return feed([]);});const queued=(await client.query(`SELECT id FROM search_runs WHERE search_id=$1 ORDER BY created_at DESC LIMIT 1`,[a.search.id])).rows[0].id;assert.equal((await client.query(`SELECT status FROM search_runs WHERE id=$1`,[queued])).rows[0].status,'QUEUED');assert.equal((await client.query(`SELECT count(*)::int n FROM search_run_results WHERE run_id=$1`,[queued])).rows[0].n,1);await client.query(`UPDATE search_run_sources SET next_fetch_at=now()-interval '1 second' WHERE run_id=$1 AND provider='arbeitnow'`,[queued]);await execution.runSearchExecutionTick(async()=>feed([]));assert.equal((await client.query(`SELECT count(*)::int n FROM search_run_results WHERE run_id=$1`,[queued])).rows[0].n,0);const results=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json();assert.equal(results.total,0);}finally{await app.close();}});

 test('source phase skips the reader when its RUNNING transition is fenced out',async()=>{const app=server();const runTrigger=`invalidate_source_start_${randomBytes(4).toString('hex')}`;const functionName=`${runTrigger}_fn`;try{const a=await createSearch(app,{providerIds:['remotive']});await client.query(`CREATE FUNCTION ${functionName}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN UPDATE search_runs SET lease_until=now()-interval '1 second' WHERE id=NEW.run_id; RETURN NULL; END $$`);await client.query(`CREATE TRIGGER ${runTrigger} BEFORE UPDATE ON search_run_sources FOR EACH ROW WHEN (NEW.status='RUNNING') EXECUTE FUNCTION ${functionName}()`);let reads=0;await execution.runSearchExecutionTick(async()=>{reads++;return feed([job()]);});assert.equal(reads,0);assert.equal((await client.query(`SELECT status FROM search_run_sources WHERE run_id=$1`,[a.runId])).rows[0].status,'QUEUED');assert.equal((await client.query(`SELECT count(*)::int n FROM jobs`)).rows[0].n,0);}finally{await client.query(`DROP TRIGGER IF EXISTS ${runTrigger} ON search_run_sources`);await client.query(`DROP FUNCTION IF EXISTS ${functionName}()`);await app.close();}});

 test('highest source score keeps matching reasons and preserves location uncertainty',async()=>{const app=server();try{const a=await createSearch(app,{location:'Spain'});const sharedUrl='https://example.test/jobs/location-uncertain';await execution.runSearchExecutionTick(async provider=>feed([job(provider,{url:sharedUrl,location:provider==='remotive'?null:'Spain'})]));const row=(await client.query(`SELECT score,reasons,location_status,unknown_location FROM search_run_results WHERE run_id=$1`,[a.runId])).rows[0];assert.equal(row.score,100);assert.equal(row.location_status,'unknown');assert.equal(row.unknown_location,true);assert.ok(row.reasons.includes('ROLE_EXACT'));assert.ok(row.reasons.includes('LOCATION_UNKNOWN'));}finally{await app.close();}});

 test('Himalayas keeps the application URL separate from provider attribution',async()=>{const app=server();try{const a=await createSearch(app,{providerIds:['himalayas']});await execution.runSearchExecutionTick(async()=>feed([job('himalayas',{url:'https://careers.fictional.com/apply/qa',raw:{__careerStackSourceUrl:'https://himalayas.app'}})]));const item=(await app.inject(`/api/v1/job-searches/${a.search.id}/results`)).json().items[0];const source=(await client.query(`SELECT source_url FROM job_search_sources WHERE provider='himalayas'`)).rows[0];const stored=(await client.query(`SELECT canonical_url FROM jobs`)).rows[0];assert.equal(stored.canonical_url,'https://careers.fictional.com/apply/qa');assert.equal(source.source_url,'https://himalayas.app');assert.equal(item.sources[0].url,'https://himalayas.app');}finally{await app.close();}});

 test('preparations are capped at five per tick and ten per installation day across workspaces',async()=>{const app=server();try{const first=await createSearch(app,{autoPrepare:true,providerIds:['remotive']});const workspace1=workspace;const workspace2=randomUUID();await client.query('INSERT INTO workspaces(id) VALUES($1)',[workspace2]);workspace=workspace2;const second=await createSearch(app,{autoPrepare:true,providerIds:['remotive']});workspace=workspace1;for(let i=0;i<6;i++){await seedPreparationMatch(first.search.id,{workspaceId:workspace1});await seedPreparationMatch(second.search.id,{workspaceId:workspace2});}const prepared:string[]=[];await execution.processV2Preparations(async(_w,id)=>{prepared.push(id);});assert.equal(prepared.length,5);await execution.processV2Preparations(async(_w,id)=>{prepared.push(id);});assert.equal(prepared.length,10);await execution.processV2Preparations(async(_w,id)=>{prepared.push(id);});assert.equal(prepared.length,10);const budgets=(await client.query<{workspace_id:string;attempted:number}>('SELECT workspace_id,attempted FROM search_preparation_budget ORDER BY workspace_id')).rows;assert.equal(budgets.reduce((n,row)=>n+row.attempted,0),10);assert.equal(budgets.length,2);assert.ok(budgets.every(row=>row.attempted>0));}finally{await app.close();}});

 test('preparation excludes archived, skipped, unknown, related, undescribed, and identity-protected jobs',async()=>{const app=server();try{const a=await createSearch(app,{autoPrepare:true,providerIds:['remotive']});const archived=await seedPreparationMatch(a.search.id,{decision:'ARCHIVED'});const skipped=await seedPreparationMatch(a.search.id,{decision:'SKIPPED'});const unknown=await seedPreparationMatch(a.search.id,{unknown:true});const related=await seedPreparationMatch(a.search.id,{title:'Automation Engineer',reasons:['ROLE_RELATED']});const undescribed=await seedPreparationMatch(a.search.id,{description:null});const closed=await seedPreparationMatch(a.search.id,{applicationState:'CONFIRMED'});const manual=await seedPreparationMatch(a.search.id,{applicationState:'READY'});const duplicateIdentity='a'.repeat(64);const first=await seedPreparationMatch(a.search.id,{identity:duplicateIdentity});const second=await seedPreparationMatch(a.search.id,{identity:duplicateIdentity});const eligible=await seedPreparationMatch(a.search.id);const prepared:string[]=[];await execution.processV2Preparations(async(_w,id)=>{prepared.push(id);});assert.equal(prepared.length,2);assert.ok(prepared.includes(eligible));assert.equal(Number(prepared.includes(first))+Number(prepared.includes(second)),1);assert.equal((await client.query(`SELECT count(*)::int n FROM saved_job_search_matches WHERE workspace_id=$1 AND job_id IN($2,$3) AND auto_prepared_at IS NOT NULL`,[workspace,first,second])).rows[0].n,2);const excluded=[archived,skipped,unknown,related,undescribed];assert.equal((await client.query(`SELECT count(*)::int n FROM saved_job_search_matches WHERE workspace_id=$1 AND job_id=ANY($2::uuid[]) AND auto_prepared_at IS NULL`,[workspace,excluded])).rows[0].n,excluded.length);const protectedRows=(await client.query(`SELECT auto_prepared_at,auto_prepare_error FROM saved_job_search_matches WHERE workspace_id=$1 AND job_id=ANY($2::uuid[])`,[workspace,[closed,manual]])).rows;assert.equal(protectedRows.length,2);assert.ok(protectedRows.every((row:{auto_prepared_at:Date|null;auto_prepare_error:string|null})=>row.auto_prepared_at===null&&row.auto_prepare_error==='EXISTING_APPLICATION'));}finally{await app.close();}});

 test('NEEDS_REVIEW, BLOCKED, and thrown preparation outcomes stay pending and retryable',async()=>{const app=server();try{const a=await createSearch(app,{autoPrepare:true,providerIds:['remotive']});const pending=await seedPreparationMatch(a.search.id);const blocked=await seedPreparationMatch(a.search.id);const failed=await seedPreparationMatch(a.search.id);let called=0;await execution.processV2Preparations(async()=>{called++;if(called===1)return {status:'NEEDS_REVIEW',reason:'NO_APPROVED_PROFILE'};if(called===2)return {status:'BLOCKED',reason:'PROFILE_INCOMPLETE'};throw new Error('fixture preparation failure');});assert.equal(called,3);const rows=(await client.query(`SELECT job_id,auto_prepared_at,auto_prepare_error,auto_prepare_attempts,auto_prepare_next_attempt_at FROM saved_job_search_matches WHERE workspace_id=$1 AND job_id=ANY($2::uuid[])`,[workspace,[pending,blocked,failed]])).rows;assert.equal(rows.length,3);assert.ok(rows.every((row:{auto_prepared_at:Date|null;auto_prepare_attempts:number;auto_prepare_next_attempt_at:Date|null})=>row.auto_prepared_at===null&&row.auto_prepare_attempts===1&&row.auto_prepare_next_attempt_at));assert.equal(rows.find((row:{job_id:string;auto_prepare_error:string|null})=>row.job_id===pending)?.auto_prepare_error,'NO_APPROVED_PROFILE');assert.equal(rows.find((row:{job_id:string;auto_prepare_error:string|null})=>row.job_id===blocked)?.auto_prepare_error,'PROFILE_INCOMPLETE');assert.equal(rows.find((row:{job_id:string;auto_prepare_error:string|null})=>row.job_id===failed)?.auto_prepare_error,'PREPARATION_FAILED');await execution.processV2Preparations(async()=>{called++;});assert.equal(called,3);}finally{await app.close();}});

 test('preparation eligibility follows the latest useful run for current criteria',async()=>{const app=server();try{const a=await createSearch(app,{autoPrepare:true,providerIds:['remotive']});const withdrawn=await seedPreparationMatch(a.search.id);const old=(await client.query(`SELECT criteria,revision FROM search_runs WHERE id=$1`,[a.runId])).rows[0];await client.query(`INSERT INTO search_runs(workspace_id,search_id,revision,criteria,status,manual,created_at,finished_at) VALUES($1,$2,$3,$4::jsonb,'SUCCEEDED',false,now()+interval '1 second',now())`,[workspace,a.search.id,old.revision,JSON.stringify(old.criteria)]);let called=0;await execution.processV2Preparations(async()=>{called++;});assert.equal(called,0);assert.equal((await client.query(`SELECT auto_prepared_at FROM saved_job_search_matches WHERE workspace_id=$1 AND job_id=$2`,[workspace,withdrawn])).rows[0].auto_prepared_at,null);}finally{await app.close();}});

 test('preparation skips stale-revision matches after search criteria change',async()=>{const app=server();try{const a=await createSearch(app,{autoPrepare:true,providerIds:['remotive']});const id=await seedPreparationMatch(a.search.id);await client.query(`UPDATE saved_job_searches SET role='Designer',revision=revision+1 WHERE workspace_id=$1 AND id=$2`,[workspace,a.search.id]);let calls=0;await execution.processV2Preparations(async()=>{calls++;});assert.equal(calls,0);assert.equal((await client.query(`SELECT auto_prepared_at FROM saved_job_search_matches WHERE workspace_id=$1 AND job_id=$2`,[workspace,id])).rows[0].auto_prepared_at,null);assert.equal((await client.query(`SELECT count(*)::int n FROM search_preparation_budget`)).rows[0].n,0);}finally{await app.close();}});

 test('requested work mode uncertainty excludes automatic preparation',async()=>{const app=server();try{const a=await createSearch(app,{autoPrepare:true,providerIds:['remotive'],workMode:'remote'});const id=await seedPreparationMatch(a.search.id,{reasons:['ROLE_EXACT','WORK_MODE_UNKNOWN']});let calls=0;await execution.processV2Preparations(async()=>{calls++;});assert.equal(calls,0);assert.equal((await client.query(`SELECT auto_prepared_at FROM saved_job_search_matches WHERE workspace_id=$1 AND job_id=$2`,[workspace,id])).rows[0].auto_prepared_at,null);}finally{await app.close();}});

 test('paused searches do not enter automatic preparation',async()=>{const app=server();try{const a=await createSearch(app,{autoPrepare:true,providerIds:['remotive']});const id=await seedPreparationMatch(a.search.id);await client.query(`UPDATE saved_job_searches SET enabled=false WHERE id=$1`,[a.search.id]);let called=0;await execution.processV2Preparations(async()=>{called++;});assert.equal(called,0);assert.equal((await client.query(`SELECT auto_prepared_at FROM saved_job_search_matches WHERE workspace_id=$1 AND job_id=$2`,[workspace,id])).rows[0].auto_prepared_at,null);}finally{await app.close();}});

 test('company-board reads require enabled verified unexpired permission and return stale timestamps honestly',async()=>{const app=server();try{const gates=[{enabled:true,association:'VERIFIED',permission:'APPROVED_FOR_SCOPE',due:'future',allow:true},{enabled:false,association:'VERIFIED',permission:'APPROVED_FOR_SCOPE',due:'future'},{enabled:true,association:'UNVERIFIED',permission:'APPROVED_FOR_SCOPE',due:'future'},{enabled:true,association:'VERIFIED',permission:'UNKNOWN',due:'future'},{enabled:true,association:'VERIFIED',permission:'APPROVED_FOR_SCOPE',due:'past'}];for(let i=0;i<gates.length;i++){const g=gates[i]!;await client.query(`INSERT INTO boards(workspace_id,provider,tenant,region,company_name,company_domain,careers_url,association_status,permission_status,enabled,reviewed_at,review_due_at,last_successful_refresh_at) VALUES($1,'greenhouse',$2,'us','Fictional','fictional.com','https://fictional.com/careers',$3,$4,$5,now(),CASE WHEN $6='future' THEN now()+interval '2 days' ELSE now()-interval '1 day' END,now()-interval '2 days') RETURNING id`,[workspace,`tenant-${i}`,g.association,g.permission,g.enabled,g.due]);const created=await client.query(`INSERT INTO jobs(workspace_id,title,company,location,canonical_url,availability) VALUES($1,'QA Engineer','Fictional','Remote','https://fictional.com/jobs/${i}','OPEN') RETURNING id`,[workspace]);await client.query(`INSERT INTO job_occurrences(workspace_id,job_id,provider,region,tenant,external_job_id,job_url,last_successful_refresh_at,source_payload) VALUES($1,$2,'greenhouse','us',$3,$4,$5,now()-interval '2 days','{}'::jsonb)`,[workspace,created.rows[0].id,`tenant-${i}`,`external-${i}`,`https://fictional.com/jobs/${i}`]);}const criteria={role:'QA',company:null,location:null,workMode:'any',matcherVersion:2,includeRelated:false,providerIds:['boards'] as SearchProvider[],language:'en' as const,frequencyHours:24};const result=await execution.readSearchSource('boards',criteria,workspace);assert.equal(result.jobs.length,1);assert.equal(result.jobs[0]?.externalId,'external-0');assert.equal(result.state,'STALE');assert.ok(result.jobs[0]?.checkedAt);assert.ok(Date.now()-Date.parse(result.jobs[0]!.checkedAt!)>24*60*60*1000);}finally{await app.close();}});

 test('company boards without a review timestamp are not authorized for search reads',async()=>{const jobId=(await client.query(`INSERT INTO jobs(workspace_id,title,company,canonical_url) VALUES($1,'QA Engineer','Fictional','https://fictional.com/jobs/unreviewed') RETURNING id`,[workspace])).rows[0].id;await client.query(`INSERT INTO boards(workspace_id,provider,tenant,region,company_name,company_domain,careers_url,association_status,permission_status,enabled,review_due_at) VALUES($1,'greenhouse','unreviewed','us','Fictional','fictional.com','https://fictional.com/careers','VERIFIED','APPROVED_FOR_SCOPE',true,now()+interval '1 day')`,[workspace]);await client.query(`INSERT INTO job_occurrences(workspace_id,job_id,provider,region,tenant,external_job_id,job_url,source_payload) VALUES($1,$2,'greenhouse','us','unreviewed','unreviewed','https://fictional.com/jobs/unreviewed','{}'::jsonb)`,[workspace,jobId]);const result=await execution.readSearchSource('boards',{role:'QA',company:null,location:null,workMode:'any',matcherVersion:2,includeRelated:false,providerIds:['boards'] as SearchProvider[],language:'en',frequencyHours:24},workspace);assert.deepEqual(result.jobs,[]);});

 test('Himalayas request budget reserves three, canonical query aliases share cooldown, and timestamps stay original',async()=>{const app=server();const original=globalThis.fetch;let calls=0;let requested:URL|undefined;try{const criteria={role:'QA',company:null,location:'Spain',workMode:'any' as const,matcherVersion:2,includeRelated:false,providerIds:['himalayas'] as SearchProvider[],language:'en' as const,frequencyHours:24};globalThis.fetch=async(input)=>{calls++;requested=new URL(String(input));return new Response(JSON.stringify({updatedAt:Date.now(),totalCount:1,limit:20,jobs:[{title:'QA Engineer',companyName:'Fictional',guid:'hima-1',applicationLink:'https://careers.fictional.com/qa',pubDate:Date.now()-1000,locationRestrictions:[],description:'Fictional description'}]}),{headers:{'content-type':'application/json'}});};const first=await execution.readSearchSource('himalayas',criteria,workspace);const budget=(await client.query(`SELECT requests FROM search_provider_budget WHERE provider='himalayas' AND day=(now() AT TIME ZONE 'UTC')::date`)).rows[0];assert.equal(budget.requests,3);assert.equal(calls,1);assert.equal(requested?.searchParams.get('q'),'qa');assert.equal(requested?.searchParams.get('country'),'ES');assert.equal(first.state,'FRESH');assert.equal(first.jobs[0]?.location,'Worldwide');const equivalent={...criteria,role:'ingeniero QA',location:'ES'};const second=await execution.readSearchSource('himalayas',equivalent,workspace);assert.equal(second.state,'CACHED');assert.equal(second.fetchedAt?.toISOString(),first.fetchedAt?.toISOString());assert.equal(calls,1);}finally{globalThis.fetch=original;await app.close();}});

 test('later-page Retry-After survives partial cache and prevents another query',async()=>{const original=globalThis.fetch;const role=`long cooldown ${randomUUID()}`;let calls=0;try{globalThis.fetch=async()=>{calls++;if(calls===1)return new Response(JSON.stringify({updatedAt:Date.parse('2026-10-03T12:00:00Z'),totalCount:100,limit:20,jobs:[{title:'QA Engineer',companyName:'Fictional',guid:'cooldown-job',applicationLink:'https://careers.fictional.com/cooldown',pubDate:Date.now()-1000,locationRestrictions:[],description:'Fictional description'}]}),{headers:{'content-type':'application/json'}});return new Response('',{status:429,headers:{'retry-after':'172800'}});};const criteria={role,company:null,location:null,workMode:'any' as const,matcherVersion:2,includeRelated:false,providerIds:['himalayas'] as SearchProvider[],language:'en' as const,frequencyHours:24};const first=await execution.readSearchSource('himalayas',criteria,workspace);assert.equal(first.coverage,'PARTIAL');const cached=(await client.query(`SELECT next_fetch_at FROM search_query_cache WHERE provider='himalayas' AND query_hash=$1`,[createHash('sha256').update(JSON.stringify({q:role.toLowerCase(),country:null})).digest('hex')])).rows[0];assert.ok(cached.next_fetch_at.getTime()>Date.now()+47*60*60*1000);const second=await execution.readSearchSource('himalayas',criteria,workspace);assert.equal(second.state,'STALE');assert.equal(calls,2);}finally{globalThis.fetch=original;}});

 test('Himalayas cooldown serves stale cached results after a failed refresh',async()=>{const criteria={role:'cached QA',company:null,location:null};const key=createHash('sha256').update(JSON.stringify({q:'cached qa',country:null})).digest('hex');const cachedJob=job('cached');const fetched=new Date(Date.now()-2*86_400_000);await client.query(`INSERT INTO search_query_cache(provider,query_hash,payload,coverage,fetched_at,next_fetch_at,error) VALUES('himalayas',$1,$2::jsonb,'PARTIAL',$3,now()+interval '1 day','SOURCE_HTTP_429')`,[key,JSON.stringify([cachedJob]),fetched]);const searchCriteria={...criteria,workMode:'any' as const,matcherVersion:2,includeRelated:false,providerIds:['himalayas'] as SearchProvider[],language:'en' as const,frequencyHours:24};const result=await execution.readSearchSource('himalayas',searchCriteria,workspace);assert.equal(result.state,'STALE');assert.equal(result.coverage,'PARTIAL');assert.equal(result.fetchedAt?.toISOString(),fetched.toISOString());assert.equal(result.jobs[0]?.externalId,'cached');});

 test('daily source budget exhaustion does not issue another request',async()=>{const original=globalThis.fetch;let calls=0;try{await client.query(`INSERT INTO search_provider_budget(provider,day,requests) VALUES('himalayas',(now() AT TIME ZONE 'UTC')::date,98) ON CONFLICT(provider,day) DO UPDATE SET requests=98`);globalThis.fetch=async()=>{calls++;return new Response('{}',{headers:{'content-type':'application/json'}});};const criteria={role:'budget check',company:null,location:null,workMode:'any' as const,matcherVersion:2,includeRelated:false,providerIds:['himalayas'] as SearchProvider[],language:'en' as const,frequencyHours:24};await assert.rejects(execution.readSearchSource('himalayas',criteria,workspace),(error:unknown)=>error instanceof ProviderReadError&&error.code==='SOURCE_DAILY_LIMIT');assert.equal(calls,0);assert.equal((await client.query(`SELECT requests FROM search_provider_budget WHERE provider='himalayas' AND day=(now() AT TIME ZONE 'UTC')::date`)).rows[0].requests,98);}finally{globalThis.fetch=original;}});

 test('source cooldown deferral lets a later eligible search progress first',async()=>{const app=server();try{const first=await createSearch(app,{role:'first',providerIds:['remotive']});const second=await createSearch(app,{role:'second',providerIds:['remotive']});const calls:string[]=[];await execution.runSearchExecutionTick(async(_p,c)=>{calls.push(c.role!);throw new ProviderReadError('SOURCE_BUSY',Date.now()+60_000);});assert.deepEqual(calls,['first']);assert.equal((await client.query('SELECT status FROM search_runs WHERE id=$1',[first.runId])).rows[0].status,'QUEUED');await execution.runSearchExecutionTick(async(_p,c)=>{calls.push(c.role!);return feed([]);});assert.deepEqual(calls,['first','second']);assert.equal((await client.query('SELECT status FROM search_runs WHERE id=$1',[second.runId])).rows[0].status,'SUCCEEDED');assert.equal((await client.query('SELECT status FROM search_runs WHERE id=$1',[first.runId])).rows[0].status,'QUEUED');}finally{await app.close();}});

 test('expired owner cannot publish after a replacement worker completes',async()=>{const app=server();try{const a=await createSearch(app,{providerIds:['remotive']});let release!:()=>void;let started!:()=>void;const waiting=new Promise<void>(r=>release=r);const ready=new Promise<void>(r=>started=r);const old=execution.runSearchExecutionTick(async()=>{started();await waiting;return feed([job('late-old')]);});await ready;await client.query(`UPDATE search_runs SET lease_until=now()-interval '1 second' WHERE id=$1`,[a.runId]);await execution.runSearchExecutionTick(async()=>feed([job('replacement')]));release();await old;assert.equal((await client.query('SELECT count(*)::int n FROM jobs')).rows[0].n,1);assert.match((await client.query('SELECT canonical_url FROM jobs')).rows[0].canonical_url,/replacement/);}finally{await app.close();}});

 test('maintenance retains the most recent successful result run even after a newer failure',async()=>{const app=server();try{const a=await createSearch(app,{providerIds:['remotive']});await execution.runSearchExecutionTick(async()=>feed([job()]));await client.query(`UPDATE search_runs SET created_at=now()-interval '31 days' WHERE id=$1`,[a.runId]);await app.inject({method:'POST',url:`/api/v1/job-searches/${a.search.id}/refresh`});const failed=(await client.query(`SELECT id FROM search_runs WHERE search_id=$1 AND id<>$2 ORDER BY created_at DESC LIMIT 1`,[a.search.id,a.runId])).rows[0].id;await client.query(`UPDATE search_runs SET status='FAILED',error='SOURCE_READ_FAILED',finished_at=now() WHERE id=$1`,[failed]);await execution.maintainSearchData();assert.equal((await client.query(`SELECT status FROM search_runs WHERE id=$1`,[a.runId])).rows[0].status,'SUCCEEDED');assert.equal((await client.query(`SELECT count(*)::int n FROM search_run_results WHERE run_id=$1`,[a.runId])).rows[0].n,1);}finally{await app.close();}});

 test('maintenance backfills invalid historical URLs without letting them starve later rows',async()=>{const ids:string[]=[];for(let i=0;i<105;i++){const id=randomUUID();ids.push(id);await client.query(`INSERT INTO jobs(id,workspace_id,title,company,canonical_url) VALUES($1,$2,'QA Engineer','Fictional',$3)`,[id,workspace,`invalid historical url ${i}`]);}await execution.maintainSearchData();await execution.maintainSearchData();const rows=(await client.query(`SELECT identity_key,evidence FROM job_identity_members WHERE workspace_id=$1 AND job_id=ANY($2::uuid[])`,[workspace,ids])).rows;assert.equal(rows.length,105);assert.equal(new Set(rows.map((row:{identity_key:string})=>row.identity_key)).size,105);assert.ok(rows.every((row:{evidence:{type:string}})=>row.evidence.type==='invalid-canonical-url'));});

 test('maintenance propagates database errors while backfilling identities',async()=>{const id=randomUUID();await client.query(`INSERT INTO jobs(id,workspace_id,title,company,canonical_url) VALUES($1,$2,'QA Engineer','Fictional',$3)`,[id,workspace,`https://jobs.fictional.example/${id}`]);await client.query(`CREATE FUNCTION fail_identity_backfill() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.job_id='${id}'::uuid THEN RAISE EXCEPTION 'fixture identity database failure'; END IF; RETURN NEW; END $$`);await client.query(`CREATE TRIGGER fail_identity_backfill_trigger BEFORE INSERT ON job_identity_members FOR EACH ROW EXECUTE FUNCTION fail_identity_backfill()`);try{await assert.rejects(execution.maintainSearchData(),/fixture identity database failure/);}finally{await client.query('DROP TRIGGER fail_identity_backfill_trigger ON job_identity_members');await client.query('DROP FUNCTION fail_identity_backfill()');}});
 test('a persisted run with missing source rows repairs its enqueue before querying', async () => {
  const app = server();
  try {
   const created = await createSearch(app, {providerIds:['remotive']});
   await client.query('DELETE FROM search_run_sources WHERE run_id=$1', [created.runId]);
   let calls = 0;
   await execution.runSearchExecutionTick(async () => { calls++; return feed([job('recovered-enqueue')]); });
   assert.equal(calls, 1);
   const response = await app.inject(`/api/v1/job-searches/${created.search.id}/results`);
   assert.equal(response.statusCode, 200, response.body);
   assert.equal(response.json().latestRun.status, 'SUCCEEDED');
   assert.equal(response.json().latestRun.sources.length, 1);
   assert.equal(response.json().total, 1);
  } finally { await app.close(); }
 });

 test('Himalayas crash reservations and host Retry-After block fresh network requests', async () => {
  const criteria = {role:'crash reservation',company:null,location:null,workMode:'any' as const,matcherVersion:2,includeRelated:false,providerIds:['himalayas'] as SearchProvider[],language:'en' as const,frequencyHours:24};
  const key = createHash('sha256').update(JSON.stringify({q:'crash reservation',country:null})).digest('hex');
  const original = globalThis.fetch; let calls = 0;
  try {
   await client.query(`DELETE FROM search_query_cache WHERE provider='himalayas'`);
   await client.query(`INSERT INTO search_query_cache(provider,query_hash,next_fetch_at) VALUES('himalayas',$1,now()+interval '24 hours')`,[key]);
   globalThis.fetch = async () => { calls++; throw new Error('must not fetch'); };
   await assert.rejects(execution.readSearchSource('himalayas',criteria,workspace),(error:unknown)=>error instanceof ProviderReadError&&error.code==='SOURCE_WAITING');
   await client.query(`UPDATE search_query_cache SET error='SOURCE_HTTP_429',next_fetch_at=now()+interval '48 hours' WHERE provider='himalayas' AND query_hash=$1`,[key]);
   await assert.rejects(execution.readSearchSource('himalayas',{...criteria,role:'different search'},workspace),(error:unknown)=>error instanceof ProviderReadError&&error.retryAt>Date.now()+47*3600000);
   assert.equal(calls,0);
  } finally {globalThis.fetch=original;}
 });

});
